language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t minchanjun/docker-play -f Dockerfile.dev . 

script:
  - docker run -e CI=true minchanjun/docker-play npm run test